name: Hadolint Linter for Docker files
description: Run hadolint linter on Dockerfile.

inputs:
  target:
    description: Target for bandit scan.
    required: false
    default: src/

runs:
  using: "composite"

  steps:
    - name: Hadolint
      shell: bash
      run: |
        docker run --rm -i ghcr.io/hadolint/hadolint < Dockerfile
